version: "3.8"

services: 

  generator-api:
    build:
      dockerfile: Dockerfile
      context: ./generator
    command: uvicorn app:app --reload --host 0.0.0.0
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    ports: 
      - "8000:8000"
    volumes:
      - /generator-temp/:/tmp

  tts-proxy-api:
    build:
      dockerfile: Dockerfile
      context: ./tts-proxy
    command: uvicorn app:app --reload --host 0.0.0.0
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - CLOUD_S3_ENDPOINT=${CLOUD_S3_ENDPOINT}
      - CLOUD_S3_ACCESS_KEY=${CLOUD_S3_ACCESS_KEY}
      - CLOUD_S3_SECRET_ACCESS_KEY=${CLOUD_S3_SECRET_ACCESS_KEY}
      - CLOUD_S3_REGION=${CLOUD_S3_REGION}
      - CLOUD_BUCKET_NAME=${CLOUD_BUCKET_NAME}
      - TTS_API_KEY_ID=${TTS_API_KEY_ID}
      - TTS_API_SECRET_KEY=${TTS_API_SECRET_KEY}
    ports: 
      - "8001:8000"

  anekdot-api:
    build:
      dockerfile: Dockerfile
      context: ./anekdoter
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DJANGO_SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
    command: sh ./run.sh
    restart: always
    depends_on:
      - database
      - tts-proxy-api
      - generator-api
    ports: 
      - "8002:8000"

  database:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  nginx:
    build:
      dockerfile: ./nginx/Dockerfile
      context: ./
    ports:
      - "80:80"