# Generated by Django 3.1.4 on 2021-02-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anekdot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('tts_hash', models.CharField(max_length=500)),
                ('rating', models.IntegerField(default=0)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField()),
                ('t', models.FloatField(blank=True)),
                ('k', models.IntegerField(blank=True)),
                ('p', models.FloatField(blank=True)),
                ('rep_penalty', models.FloatField(blank=True)),
            ],
        ),
    ]
