# Generated by Django 3.1.7 on 2021-03-03 14:20

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anekdot',
            name='k',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='anekdot',
            name='p',
            field=models.FloatField(blank=True, default=0.92),
        ),
        migrations.AlterField(
            model_name='anekdot',
            name='rep_penalty',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='anekdot',
            name='t',
            field=models.FloatField(blank=True, default=0.9),
        ),
        migrations.CreateModel(
            name='AnekUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('rated_aneks', models.ManyToManyField(blank=True, to='models.Anekdot')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
